firehydrant/design-system

- .gitignore
- lib/components/button/Button.stories.js
According to this article: https://storybook.js.org/docs/react/writing-docs/doc-blocks#docspage-1
There is a way to configure stories to display generated snippets on the DocsPage instead of source. Maybe we can find a way to apply this automatically to all stories; in a template perhaps? Something to work off of.
> Replaces source with rendered code in docspage

- lib/components/checkbox/CheckboxGroup.jsx
- lib/components/radio/RadioGroup.jsx
Just decreases vertical spacing for radio and checkbox groups from `2px (sg0) from 8px (s1)`
[Update vertical alignment gap for Checkbox and Radio to 2px](https://app.clubhouse.io/firehydrant/story/17938/update-vertical-alignment-gap-for-checkbox-and-radio-to-2px)
> decrease vertical spacing

- lib/components/container/Container.jsx
- lib/components/container/Container.stories.js
- lib/components/container/container.theme.js
- lib/components/container/index.js
- lib/main.js
- lib/theme/index.js
Adds container component with two provided sizes: `1100px` and `1400px` maxWidth. 
By default, without the `size` prop, the component will constrain to 60ch- I feel this is an acceptable fall back because it falls within the optimal legibility range for text.
> Add container component

- lib/components/button/Button.stories.js
- lib/components/button/button.theme.js
This hack was put into place when we still had the icon being flexed to the end but wanted the loading indicator to work correctly. This is no longer needed since Chakra updated to always have the icon centered.
> Remove unused prop

- lib/components/tabs/tabs.theme.js
I noticed that since our storybook is white you can't see this but when implementing tabs in laddertruck since their isn't a default background color it goes with the default greyish background. Tabs should always be  grey.0 to start.
> set default tab bg color

- lib/components/table/table.theme.js
Box Shadow doesn't work on tr elements in safari so this switches it up to use border-bottom as Chakra already was using before.
> switch to border bottom as safari doesn't allow for box-shadow on tr elements

- CHANGELOG.md
- lib/components/link/Link.stories.js
- lib/components/link/link.theme.js
- lib/components/link/linktext.theme.js
- package.json
Basically there was an issues with Links not wrapping correctly 
As well as an underline still appearing. This PR fixes both of those issues and adds it the changelog and bumps the version.
[Issue with Link text not following underline as well as hover state still showing an underline.](https://app.clubhouse.io/firehydrant/story/19042/issue-with-link-text-not-following-underline-as-well-as-hover-state-still-showing-an-underline)
> Minor fixes for links

- lib/components/checkbox/Checkbox.jsx
- lib/components/checkbox/CheckboxGroup.jsx
- lib/components/link/Link.jsx
- lib/components/radio/Radio.jsx
- lib/components/radio/RadioGroup.jsx
[SPIKE: Swap `sx` for `__css` in components](https://app.clubhouse.io/firehydrant/story/19036/spike-swap-sx-for-css-in-components)
> Add the correct syntax to switch to __css

- .github/workflows/chromatic.yml
Adds the `onlyChanged` flag to the chromatic GitHub action; this is a
requirement for TurboSnaps (Chromatic) to work properly.
Reference: https://www.chromatic.com/docs/turbosnap
> Enables TurboSnaps

- .gitmessage
- CONTRIBUTING.md
- README.md
- package-lock.json
- package.json
Automatic CHANGELOG generation & intelligent (automatic) version bumping per semver specification powered by [`standard-version`](https://github.com/conventional-changelog/standard-version). 
**NOTE**: This PR requires `npm install` 
* Contribution documentation to reflect this change
* `standard-version` package added to project
* `postinstall` script added which injects `git commit` message template into `gitconfig --local`
* `.gitmessage` template added to aid contributor with forming commit messages according to Conventional Commit standard
Preview of `git commit` message template:
I elected to go with a no-enforcement policy on the commit message structure. 
Currently, if a contributor does not abide by the Conventional Commit standard, it won't get picked up in any meaningful way …
> Conventional commits, automatic changelog generation & version bumping

- .gitignore
- lib/components/button/button.theme.js
This change removes the x-spacing (padding) from the tertiary Button
variant. It was discovered through design testing, that having this
extra negative space was doing more harm than good and would more than
likely result in overrides. See #[19508](https://app.clubhouse.io/firehydrant/story/19508/remove-x-spacing-from-tertiary-variant) for more details.
NOTE: This change will cause visual shifts on all instances of tertiary
button.
> fix(button): Remove x-spacing from tertiary variant

- package-lock.json
- package.json
This attempts to address an issue in our docker environments, preventing
successful installation due to the postinstall script.
`git-message` should take the place of the postinstall script, achieving effectively the same desired outcome but eliminating what appears to be a problematic script (for docker environment).
> fix: Remove postinstall script

- .github/workflows/chromatic.yml
- .gitignore
- .npmrc
- README.md
- package-lock.json
- package.json
This change includes a minor rewrite of git history changing previous
version bump commits by dependabot into `bump` types. Now the changelog
will be generated with a chores and version bump section populated by
changes of each type respectively.
Example of new changelog generated by this:
> docs: Adds version bumps to changelog generation

- .all-contributorsrc
- .github/workflows/chromatic.yml
- CONTRIBUTING.md
- README.md
The Chromatic action in GitHub will not be able to run on dependabot triggered branches according to this change: https://github.com/dependabot/dependabot-core/issues/3253
As such, we are reverting back to ignoring `dependabot` triggered branches in the Chromatic action. 
**TODO**
> chore: Revert chromatic action

- lib/components/checkbox/Checkbox.stories.js
- lib/components/radio/Radio.stories.js
defaultIsChecked as a prop for Checkbox & Radio has been deprecated by
Chakra. Update docs to reflect this change.
BREAKING CHANGE: `defaultIsChecked` is deprecated; use `defaultChecked`
> fix(radio, checkbox): Deprecate defaultIsChecked

- lib/components/table/Table.stories.js
- lib/components/tag/Tag.stories.js
- lib/components/tag/tag.theme.js
- lib/recipes/LogInForm/Tags.stories.js
This adds the outline variant styling to the Tag component. As a side
effect, the previous values for the `variant` prop are no longer valid.
Tag has been refactored to use the Chakra paradigm of `variant` and
`colorScheme` to choose a visual styling for Tag.
Valid values for `variant` are now: outline, subtle; `colorScheme` is
any valid color family from the foundations.
BREAKING CHANGE: any previous `variant` value is no longer valid. Tag
now expects `variant='[subtle | outline]'` and
`colorScheme='<foundation_color_family>'`.
--
Todo:
> feat(tag): adds outline variant

- lib/main.js
Stack (HStack, VStack) require a special divider to function properly.
> feat(StackDivider): adds StackDivider

- lib/components/dropdown/Dropdown.jsx
React Select sets `maxMenuHeight` to 300 by default, but as we were not passing the provided styles to our customStyles, the max-height was not being set. This fix can be seen in the "Searchable Options" and async stories.
> fix(Dropdown): pass provided styles to MenuList to set maxMenuHeight

- lib/components/button/button.theme.js
Having 0px padding on the x-axis for the tertiary variant was causing a
lot of negative feedback. 8px (spacing: 2) has been added on the x-axis
to improve aesthetics.
> fix(Button): adds 8px x-padding to tertiary variant

- lib/components/alert/Alert.jsx
- lib/components/alert/Alert.stories.js
- lib/theme/space.stories.mdx
- lib/theme/storybookBlocks.jsx
_tl;dr adds custom storybook components for space & radii display; adds a fix to `Alert` to handle `...rest` prop_
In addition to adding a story to display the Space & Radii tokens, this change introduces custom storybook component blocks to aid in display of that information. 
Upon writing stories for Space, a bug in `<Alert>` was discovered that prevented passing [style props](https://chakra-ui.com/docs/features/style-props) to the component because the `...rest` prop was unhandled. This change now properly spreads that prop on the container.
> docs(Storybook): custom blocks for space & radius

- lib/main.js
I would like to use the Accordion components from Chakra instead of the react-strap Collapse currently in Laddertruck.
> feat(accordion): add exports of Accordion components from Chakra

- lib/components/alert/Alert.jsx
- lib/components/alert/Alert.stories.js
- lib/components/alert/alert.theme.js
Add new color treatment for "notice" alerts, used in notifications for advanced trial. See GitHub issue [here](https://github.com/firehydrant/laddertruck/issues/4209).
> feature(alert): add new 'notice' theme to alert

- lib/components/tabs/tabs.theme.js
- package.json
Per review by design, the inactive tabs should not have the default background grey color, and we don't want enclosed tabs to have the purple underline on hover.
https://user-images.githubusercontent.com/10586810/162509899-f4a92027-4127-48a1-941f-999b4f585c40.mov
> Remove underline on hover. Make inactive tab backgrounds transparent.

- lib/components/dropdown/Dropdown.jsx
- lib/components/dropdown/Dropdown.stories.js
Text in dropdowns was not aligned properly after react-select upgrade.
**Chromatic link**
https://607731addb01d30021caeac2-tgrgypthbw.chromatic.com/?path=/story/components-forms-dropdown--default-with-value
**Before:** 
https://user-images.githubusercontent.com/10586810/163841603-38d04ce4-9dfa-419e-bf98-5946f5659413.mov
**After:**
https://user-images.githubusercontent.com/10586810/163841701-d3d65cd6-924a-4b15-987c-890f502a8289.mov
**New story with value**
> Fix vertical alignment of value in dropdown.

- lib/components/popover/index.js
- lib/main.js
Exporting components made [here](https://github.com/firehydrant/design-system/pull/249).
> fix(popover): export components

- lib/main.js
Add `AspectRatio` in anticipation of a responsive video walkthrough component.
> chore(AspectRatio): add AspectRatio to chakra exports
