.storybook/preview.js
lib/components/link/Link.jsx
lib/components/link/Link.stories.js
lib/components/link/LinkText.js
lib/components/link/index.js
lib/components/link/link.theme.js
lib/components/link/linktext.theme.js
lib/main.js
lib/theme/index.js

Adds the link component to the design system with the proper design specs from https://www.figma.com/file/5Kra5sXVMkAjM62Gh8DpM8/Draft-Documentation?node-id=201%3A11

DS: Build Link

---

lib/components/tabs/Tabs.jsx
lib/components/tabs/Tabs.stories.js
lib/components/tabs/index.js
lib/components/tabs/tabs.theme.js
lib/main.js
lib/theme/index.js

Adds the Tabs component as well as associated layout components within the Tabs component. Tabs, TabList, TabPanels, Tab, TabPanel .

DS: Build Tabs

---

.storybook/preview.js
lib/components/divider/Divider.jsx
lib/components/divider/Divider.stories.js
lib/components/divider/divider.theme.js
lib/components/divider/index.js
lib/main.js
lib/theme/index.js

Adds the basic divider component and storybook examples.

DS: Build Divider

---

lib/components/button/button.theme.js

Fixes issue with border not showing up on disabled state.

Fix border on secondary disabled

---

CHANGELOG.md
lib/components/textfield/TextField.stories.js
lib/theme/index.js
package-lock.json
package.json
playroom.config.js

[add breakpoints to theme](https://app.clubhouse.io/firehydrant/story/18422)

add breakpoints to theme and increment version to new release

---

lib/components/table/Table.jsx
lib/components/table/Table.stories.js
lib/components/table/index.js
lib/components/table/table.theme.js
lib/main.js
lib/theme/index.js

This PR introduces Tables
[DS: Build Table (Basic)](https://app.clubhouse.io/firehydrant/story/14042/ds-build-table-basic)

DS: Build (Basic) Table

---

README.md

Updates the readme with publish instructions

Update readme with publish instructions.

---

.github/workflows/chromatic.yml
README.md
lib/components/divider/Divider.stories.js
lib/components/switch/Switch.stories.js
package-lock.json
package.json
vite.config.js

Make sure we aren't bundling in React for sure now. Thanks to @caseymhunt for finding this out.

Make react a peer dep and update readme for publishing with latest flag

---

lib/components/link/LinkText.jsx

[Dom Nesting error with new Link component](https://app.clubhouse.io/firehydrant/story/19035/dom-nesting-error-with-new-link-component)
props to @hizegi for finding this one.

use span for correct nesting

---

lib/components/iconbutton/IconButton.stories.js
lib/components/link/Link.stories.js
lib/components/switch/Switch.stories.js
lib/components/table/Table.stories.js
lib/components/tabs/Tabs.stories.js

Clubhouse ticket: https://app.clubhouse.io/firehydrant/story/19121/organize-storybook-stories

Re-organizes stories per Design

---

package-lock.json
playroom.config.js

This adds another width option to the Playroom config which uses the CSS
`calc` function to create a responsive window width. It's ugly but it
works.
Demo of it working:

chore(playroom): Adds responsive width

---

.gitignore
.npmrc
README.md

Including .npmrc removes a step from the setup process.

chore: Include .npmrc in project

---

lib/components/button/button.theme.js
lib/components/card/card.theme.js
lib/components/checkbox/checkbox.theme.js
lib/components/iconbutton/IconButton.jsx
lib/components/link/link.theme.js
lib/components/link/linktext.theme.js
lib/components/tabs/tabs.theme.js
lib/components/tag/tag.theme.js
lib/components/textfield/textfield.theme.js
lib/recipes/LogInForm/LogInForm.stories.js
lib/theme/radii.theme.js
package-lock.json

This change adds approved border radius values to our FireHydrant theme,
current valid values are [none, sm, base / md, lg, full]. This also
addresses a 2px discrepancy from the design-spec'd radius for
iconButton.
NOTE: IconButton will now have 4px radius instead of 6px.

feat(theme): adds border radius to theme

---

lib/components/alert/Alert.jsx
lib/components/alert/Alert.stories.js
lib/components/alert/alert.theme.js
lib/components/alert/index.js
lib/main.js
lib/theme/index.js
lib/theme/space.theme.js

[DS: Build Alert](https://app.clubhouse.io/firehydrant/story/18132/ds-build-alert)
Adds the alert component and stories.

feat(alert): build alert component

---

lib/components/tag/Tag.jsx
lib/components/tag/Tag.stories.js

* adjusts margin for `TagRightIcon` sub-component
* adds story for tag with an icon on the right

fix(tag): Corrects margin for right-aligned icon

---

.all-contributorsrc
package-lock.json

All contributors somehow managed to get a malformed JSON config file.
Re-wrote in proper syntax. Also adding an updated package-lock which
contains the correct version (2.3.0).

docs(all-contributors): Fixing malformed config

---

lib/main.js

Chakra documentation for Wrap: https://chakra-ui.com/docs/layout/wrap

feat(Wrap): adds Wrap layout component.

---

lib/main.js

Adds the Center layout component (https://chakra-ui.com/docs/layout/center) from Chakra.
Also adds Square & Center helper components (https://chakra-ui.com/docs/layout/center#square-and-circle)
--

feat(Center): adds Center (Square, Circle)

---

lib/components/alert/Alert.jsx

Imported custom theme overrides class styles on Alert component (remember cascading?). Fixes order of style rules and declares mb=0 on child text.

fix(alert): corrects borders and margin on text

---

lib/components/alert/Alert.jsx

Add `borderStyle` to inline style rules.

fix(alert): add border style to alert

---

lib/helpers/Transitions.stories.js
lib/main.js

Adds Collapse, Fade, ScaleFade, Slide, SlideFade, and useDisclosure
(hook)

feat(Transitions): adds Transitions components

---

README.md

We're working to add some consistency to our public repositories on GitHub. This introduces some minor changes to the top part that centers it and adds our logo.

Update readme to have consistency for public repos

---

lib/components/menu/Menu.jsx
lib/components/menu/Menu.stories.js
lib/components/menu/MenuGroup.jsx
lib/components/menu/MenuItem.jsx
lib/components/menu/index.js
lib/components/menu/menu.theme.js
lib/main.js
lib/theme/index.js

[DS: Build Menu](https://app.clubhouse.io/firehydrant/story/16669/ds-build-menu)
Adds the Menu, MenuGroup, and MenuItem components.

feat(Menu): builds Menu component

---

lib/components/button/Button.stories.js
lib/components/button/button.theme.js

[Button: Danger variant](https://app.clubhouse.io/firehydrant/story/22699/button-danger-variant)
Adds Danger variant to Button component.

feat(ButtonDanger): adds Button Danger variant to Button

---

lib/components/breadcrumb/Breadcrumb.jsx
lib/components/breadcrumb/Breadcrumb.stories.js
lib/components/breadcrumb/index.js
lib/components/menu/Menu.jsx
lib/components/menu/Menu.stories.js
lib/main.js

[Breadcrumb](https://app.shortcut.com/firehydrant/story/22641/breadcrumb)
Adds Breadcrumb component.

feat(Breadcrumb): adds Breadcrumb

---

lib/components/checkbox/checkbox.theme.js
lib/components/icons/Icon.jsx
package.json

Fixes the issue where our app was causing problems with unknown props being passed to the checkbox. Additionally this speeds up our spec times.

Fix checkbox

---

lib/main.js
package-lock.json
package.json

Testing hilary's changes, just in a different branch

Add ModalCloseButton

---

lib/components/tabs/tabs.theme.js

https://user-images.githubusercontent.com/10586810/163276807-a2d73f9e-bc4a-487d-aefa-08bf4a856ab4.mov

Tabs - polish fixes per design review on service dependencies

---

lib/components/tabs/tabs.theme.js

Make border radius on tabs smaller

---

lib/components/popover/PopoverBasis.jsx
lib/components/popover/PopoverDialog.jsx
lib/components/popover/PopoverDialog.stories.js
lib/components/popover/PopoverInput.jsx
lib/components/popover/PopoverInput.stories.js
lib/components/popover/Popovers.spec.jsx
lib/components/popover/index.js

[Chromatic](https://607731addb01d30021caeac2-qcuwyxnhne.chromatic.com/?path=/story/components-popover--popover-dialog-default) 
[Figma specs](https://www.figma.com/file/5Kra5sXVMkAjM62Gh8DpM8/Draft-Documentation?node-id=4653%3A4996)

Popovers for dialog or inputs

---

lib/components/textfield/TextField.stories.js
lib/main.js
package.json

Adding in right element from chakra with an example

Right element
